export enum ActionType {
    SET_START_DATE = 'SET_START_DATE',
    SET_RETURN_DATE = 'SET_RETURN_DATE',
    SET_STORE = 'SET_STORE',
    SET_USER_INFO = 'SET_USER_INFO',
    SET_IMAGE_URLS = 'SET_IMAGE_URLS',
    SET_SELECTED_INDEX = 'SET_SELECTED_INDEX'
}